### ISSUE TITLE
ASFW License

### ISSUE THREAD

**Issue by SpiceyWolf** [Xlithan/MirageBasic#1]
This is the official repo of asfw, linked specifically to the license. Eclipse DOES NOT and has NEVER owned my source code. I have never given permission for license to be changed either.

ASFW stands for Archaicsoft Framework.

https://gitlab.com/ArchaicSoft/miscellaneous/Asfw-CS/-/blob/master/LICENSE

**Comment by Xlithan** [comment]
Hi Damien,

MirageBasic is based off Orion+ which was converted from Eclipse Origins by JC Snider. Most of the contents of the project have not been changed from that project yet, but I will endeavour to address the issue of ASFW licensing as soon as possible.

Kind regards,
Xlithan.

**Comment by SpiceyWolf** [comment]
I understand that, i contributed to orion and am the one who swapped it onto asfw for massive performance gains over the original systems...

Im not the happiest that an eclipse license was tacked onto it however, as the orion engine used it in nuget package which DID include a "read if you care" notice on import with the proper license.

Id prefer that get fixed sooner than later, I've gotten fed up with attacks on me in discord claiming I stole some other code that I wrote because people are ignorant. (Though they were unrelated to this specifically I do not wish to see this become another vector).

**Comment by SpiceyWolf** [comment]
all good, thnx
